-- ============================================
-- RESTAURANT PLATFORM - INITIAL SCHEMA
-- ============================================
-- Multi-restaurant platform with master catalog architecture
-- Version: 1.0.0 - Consolidated schema

-- ============================================
-- ORGANIZATION & RESTAURANTS
-- ============================================

CREATE TABLE organization (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(250) NOT NULL,
    company_name    VARCHAR(250) NOT NULL,
    ruc             VARCHAR(20),
    phone           VARCHAR(30),
    email           VARCHAR(120),
    address         TEXT,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT ck_organization__name_not_blank CHECK (length(trim(name)) > 0),
    CONSTRAINT ck_organization__company_name_not_blank CHECK (length(trim(company_name)) > 0)
);

CREATE UNIQUE INDEX uk_organization__ruc ON organization (ruc) WHERE ruc IS NOT NULL;
COMMENT ON TABLE organization IS 'Organizations (empresas) - top level entity';

CREATE TABLE restaurant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    name            VARCHAR(250) NOT NULL,
    company_name    VARCHAR(250),
    ruc             VARCHAR(20),
    phone           VARCHAR(30),
    email           VARCHAR(120),
    address         TEXT,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_restaurant__organization FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT ck_restaurant__name_not_blank CHECK (length(trim(name)) > 0)
);

CREATE INDEX idx_restaurant__organization_id ON restaurant (organization_id);
CREATE UNIQUE INDEX uk_restaurant__organization_name ON restaurant (organization_id, name);
COMMENT ON TABLE restaurant IS 'Restaurants (sedes) - multiple per organization';

-- ============================================
-- USERS & ACCESS CONTROL
-- ============================================

CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    username        VARCHAR(50) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    first_name      VARCHAR(50) NOT NULL,
    last_name       VARCHAR(50) NOT NULL,
    email           VARCHAR(120),
    phone           VARCHAR(30),
    role            VARCHAR(20) NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_app_user__organization FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT ck_app_user__username_not_blank CHECK (length(trim(username)) > 0),
    CONSTRAINT ck_app_user__first_name_not_blank CHECK (length(trim(first_name)) > 0),
    CONSTRAINT ck_app_user__last_name_not_blank CHECK (length(trim(last_name)) > 0)
);

CREATE INDEX idx_app_user__organization_id ON app_user (organization_id);
CREATE UNIQUE INDEX uk_app_user__organization_username ON app_user (organization_id, username);
COMMENT ON TABLE app_user IS 'Users - belong to organization, can access multiple restaurants';

CREATE TABLE user_restaurant_access (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    restaurant_id   BIGINT NOT NULL,
    role            VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_user_restaurant_access__app_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_restaurant_access__restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant(id) ON DELETE CASCADE,
    CONSTRAINT ck_user_restaurant_access__role CHECK (role IN ('ADMIN', 'WAITER', 'CASHIER', 'KITCHEN')),
    CONSTRAINT uk_user_restaurant_access__user_restaurant UNIQUE (user_id, restaurant_id)
);

CREATE INDEX idx_user_restaurant_access__user_id ON user_restaurant_access (user_id);
CREATE INDEX idx_user_restaurant_access__restaurant_id ON user_restaurant_access (restaurant_id);
COMMENT ON TABLE user_restaurant_access IS 'User access to restaurants with roles';

-- ============================================
-- MASTER CATALOG (ORGANIZATION-LEVEL)
-- ============================================

CREATE TABLE master_product_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    name            VARCHAR(80) NOT NULL,
    description     TEXT,
    display_order   INTEGER DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_master_product_category__organization FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT ck_master_product_category__name_not_blank CHECK (length(trim(name)) > 0),
    CONSTRAINT uk_master_product_category__organization_name UNIQUE (organization_id, name)
);

CREATE INDEX idx_master_product_category__organization_id ON master_product_category (organization_id);
CREATE INDEX idx_master_product_category__display_order ON master_product_category (display_order);
COMMENT ON TABLE master_product_category IS 'Master product categories - single source of truth for organization';

CREATE TABLE master_product (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id     BIGINT NOT NULL,
    master_category_id  BIGINT NOT NULL,
    code                VARCHAR(50),
    name                VARCHAR(150) NOT NULL,
    description         TEXT,
    base_price          NUMERIC(10,2) NOT NULL,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          BIGINT,
    updated_by          BIGINT,

    CONSTRAINT fk_master_product__organization FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT fk_master_product__master_category FOREIGN KEY (master_category_id) REFERENCES master_product_category(id),
    CONSTRAINT ck_master_product__name_not_blank CHECK (length(trim(name)) > 0),
    CONSTRAINT ck_master_product__base_price_positive CHECK (base_price >= 0),
    CONSTRAINT uk_master_product__organization_name UNIQUE (organization_id, name)
);

CREATE INDEX idx_master_product__organization_id ON master_product (organization_id);
CREATE INDEX idx_master_product__master_category_id ON master_product (master_category_id);
CREATE UNIQUE INDEX uk_master_product__organization_code ON master_product (organization_id, code) WHERE code IS NOT NULL;
COMMENT ON TABLE master_product IS 'Master products - single source of truth (name, description, base_price)';

CREATE TABLE master_menu_template (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    name            VARCHAR(120) NOT NULL,
    description     TEXT,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_master_menu_template__organization FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT ck_master_menu_template__name_not_blank CHECK (length(trim(name)) > 0),
    CONSTRAINT uk_master_menu_template__organization_name UNIQUE (organization_id, name)
);

CREATE INDEX idx_master_menu_template__organization_id ON master_menu_template (organization_id);
COMMENT ON TABLE master_menu_template IS 'Master menu templates - shared across organization';

CREATE TABLE master_menu_template_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_template_id  BIGINT NOT NULL,
    master_product_id   BIGINT NOT NULL,
    display_order       INTEGER DEFAULT 0,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          BIGINT,
    updated_by          BIGINT,

    CONSTRAINT fk_master_menu_template_item__master_template FOREIGN KEY (master_template_id) REFERENCES master_menu_template(id) ON DELETE CASCADE,
    CONSTRAINT fk_master_menu_template_item__master_product FOREIGN KEY (master_product_id) REFERENCES master_product(id),
    CONSTRAINT uk_master_menu_template_item__template_product UNIQUE (master_template_id, master_product_id)
);

CREATE INDEX idx_master_menu_template_item__master_template_id ON master_menu_template_item (master_template_id);
CREATE INDEX idx_master_menu_template_item__master_product_id ON master_menu_template_item (master_product_id);
COMMENT ON TABLE master_menu_template_item IS 'Items in master menu templates';

-- ============================================
-- RESTAURANT-SPECIFIC DATA
-- ============================================

CREATE TABLE product (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id       BIGINT NOT NULL,
    master_product_id   BIGINT NOT NULL,
    price               NUMERIC(10,2) NOT NULL,
    available           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          BIGINT,
    updated_by          BIGINT,

    CONSTRAINT fk_product__restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant(id),
    CONSTRAINT fk_product__master_product FOREIGN KEY (master_product_id) REFERENCES master_product(id),
    CONSTRAINT ck_product__price_positive CHECK (price >= 0),
    CONSTRAINT uk_product__restaurant_master_product UNIQUE (restaurant_id, master_product_id)
);

CREATE INDEX idx_product__restaurant_id ON product (restaurant_id);
CREATE INDEX idx_product__master_product_id ON product (master_product_id);
COMMENT ON TABLE product IS 'Restaurant-specific product data - only price and availability';
COMMENT ON COLUMN product.master_product_id IS 'REQUIRED: Link to master catalog for name/description';
COMMENT ON COLUMN product.price IS 'Restaurant-specific price (may differ from base_price)';
COMMENT ON COLUMN product.available IS 'Restaurant-specific availability';

CREATE TABLE daily_menu (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id           BIGINT NOT NULL,
    master_template_id      BIGINT,
    menu_date               DATE NOT NULL,
    menu_price              NUMERIC(10,2) NOT NULL,
    active                  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_by              BIGINT,

    CONSTRAINT fk_daily_menu__restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant(id),
    CONSTRAINT fk_daily_menu__master_template FOREIGN KEY (master_template_id) REFERENCES master_menu_template(id),
    CONSTRAINT ck_daily_menu__price_positive CHECK (menu_price >= 0),
    CONSTRAINT uk_daily_menu__restaurant_date UNIQUE (restaurant_id, menu_date)
);

CREATE INDEX idx_daily_menu__restaurant_id ON daily_menu (restaurant_id);
CREATE INDEX idx_daily_menu__menu_date ON daily_menu (menu_date);
CREATE INDEX idx_daily_menu__master_template_id ON daily_menu (master_template_id);
COMMENT ON TABLE daily_menu IS 'Daily menus per restaurant';

CREATE TABLE daily_menu_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_menu_id   BIGINT NOT NULL,
    product_id      BIGINT NOT NULL,
    price_override  NUMERIC(10,2),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_daily_menu_item__daily_menu FOREIGN KEY (daily_menu_id) REFERENCES daily_menu(id) ON DELETE CASCADE,
    CONSTRAINT fk_daily_menu_item__product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT ck_daily_menu_item__price_positive CHECK (price_override IS NULL OR price_override >= 0),
    CONSTRAINT uk_daily_menu_item__menu_product UNIQUE (daily_menu_id, product_id)
);

CREATE INDEX idx_daily_menu_item__daily_menu_id ON daily_menu_item (daily_menu_id);
CREATE INDEX idx_daily_menu_item__product_id ON daily_menu_item (product_id);
COMMENT ON TABLE daily_menu_item IS 'Items in daily menu';

CREATE TABLE restaurant_table (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id   BIGINT NOT NULL,
    number          VARCHAR(20) NOT NULL,
    capacity        INTEGER NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_restaurant_table__restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant(id),
    CONSTRAINT ck_restaurant_table__number_not_blank CHECK (length(trim(number)) > 0),
    CONSTRAINT ck_restaurant_table__capacity_positive CHECK (capacity > 0),
    CONSTRAINT ck_restaurant_table__status CHECK (status IN ('AVAILABLE', 'OCCUPIED', 'RESERVED', 'UNAVAILABLE')),
    CONSTRAINT uk_restaurant_table__restaurant_number UNIQUE (restaurant_id, number)
);

CREATE INDEX idx_restaurant_table__restaurant_id ON restaurant_table (restaurant_id);
COMMENT ON TABLE restaurant_table IS 'Tables per restaurant';

-- ============================================
-- ORDER MANAGEMENT
-- ============================================

CREATE TABLE order_table (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id   BIGINT NOT NULL,
    waiter_id       BIGINT NOT NULL,
    table_id        BIGINT,
    order_number    VARCHAR(50) NOT NULL,
    order_type      VARCHAR(20) NOT NULL DEFAULT 'DINE_IN',
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    subtotal        NUMERIC(10,2) NOT NULL DEFAULT 0,
    total           NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_order_table__restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant(id),
    CONSTRAINT fk_order_table__waiter FOREIGN KEY (waiter_id) REFERENCES app_user(id),
    CONSTRAINT fk_order_table__table FOREIGN KEY (table_id) REFERENCES restaurant_table(id),
    CONSTRAINT ck_order_table__number_not_blank CHECK (length(trim(order_number)) > 0),
    CONSTRAINT ck_order_table__status CHECK (status IN ('PENDING', 'IN_PREPARATION', 'READY', 'DELIVERED', 'PAID', 'CANCELLED')),
    CONSTRAINT ck_order_table__order_type CHECK (order_type IN ('DINE_IN', 'TAKE_AWAY', 'DELIVERY')),
    CONSTRAINT ck_order_table__subtotal_positive CHECK (subtotal >= 0),
    CONSTRAINT ck_order_table__total_positive CHECK (total >= 0),
    CONSTRAINT uk_order_table__restaurant_number UNIQUE (restaurant_id, order_number)
);

CREATE INDEX idx_order_table__restaurant_id ON order_table (restaurant_id);
CREATE INDEX idx_order_table__waiter_id ON order_table (waiter_id);
CREATE INDEX idx_order_table__table_id ON order_table (table_id);
CREATE INDEX idx_order_table__status ON order_table (status);
CREATE INDEX idx_order_table__created_at ON order_table (created_at);
COMMENT ON TABLE order_table IS 'Orders - renamed from "order" to avoid SQL keyword conflict';

CREATE TABLE order_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL,
    product_id      BIGINT NOT NULL,
    quantity        INTEGER NOT NULL,
    unit_price      NUMERIC(10,2) NOT NULL,
    subtotal        NUMERIC(10,2) NOT NULL,
    notes           TEXT,
    is_part_of_menu BOOLEAN DEFAULT FALSE,
    menu_group_id   BIGINT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,

    CONSTRAINT fk_order_item__order FOREIGN KEY (order_id) REFERENCES order_table(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item__product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT ck_order_item__quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_order_item__unit_price_positive CHECK (unit_price >= 0),
    CONSTRAINT ck_order_item__subtotal_positive CHECK (subtotal >= 0)
);

CREATE INDEX idx_order_item__order_id ON order_item (order_id);
CREATE INDEX idx_order_item__product_id ON order_item (product_id);
COMMENT ON TABLE order_item IS 'Items in an order';

-- ============================================
-- PAYMENT SYSTEM
-- ============================================

CREATE TABLE payment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id   BIGINT NOT NULL,
    table_id        BIGINT NOT NULL,
    waiter_id       BIGINT NOT NULL,
    paid_by_id      BIGINT NOT NULL,
    payment_number  VARCHAR(50) NOT NULL,
    subtotal        NUMERIC(10,2) NOT NULL,
    igv_amount      NUMERIC(10,2) NOT NULL,
    total_amount    NUMERIC(10,2) NOT NULL,
    paid_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observations    TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment__restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant(id),
    CONSTRAINT fk_payment__table FOREIGN KEY (table_id) REFERENCES restaurant_table(id),
    CONSTRAINT fk_payment__waiter FOREIGN KEY (waiter_id) REFERENCES app_user(id),
    CONSTRAINT fk_payment__paid_by FOREIGN KEY (paid_by_id) REFERENCES app_user(id),
    CONSTRAINT ck_payment__subtotal_positive CHECK (subtotal >= 0),
    CONSTRAINT ck_payment__igv_positive CHECK (igv_amount >= 0),
    CONSTRAINT ck_payment__total_positive CHECK (total_amount >= 0),
    CONSTRAINT uk_payment__restaurant_number UNIQUE (restaurant_id, payment_number)
);

CREATE INDEX idx_payment__restaurant_id ON payment (restaurant_id);
CREATE INDEX idx_payment__table_id ON payment (table_id);
CREATE INDEX idx_payment__paid_at ON payment (paid_at);
COMMENT ON TABLE payment IS 'Payments for orders';

CREATE TABLE payment_method_detail (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id          BIGINT NOT NULL,
    payment_method      VARCHAR(20) NOT NULL,
    amount              NUMERIC(10,2) NOT NULL,
    amount_received     NUMERIC(10,2),
    change_given        NUMERIC(10,2),

    CONSTRAINT fk_payment_method_detail__payment FOREIGN KEY (payment_id) REFERENCES payment(id) ON DELETE CASCADE,
    CONSTRAINT ck_payment_method_detail__method CHECK (payment_method IN ('CASH', 'CARD', 'YAPE', 'PLIN', 'TRANSFER')),
    CONSTRAINT ck_payment_method_detail__amount_positive CHECK (amount >= 0)
);

CREATE INDEX idx_payment_method_detail__payment_id ON payment_method_detail (payment_id);
COMMENT ON TABLE payment_method_detail IS 'Payment methods used in a payment';

CREATE TABLE payment_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id      BIGINT NOT NULL,
    order_id        BIGINT NOT NULL,

    CONSTRAINT fk_payment_order__payment FOREIGN KEY (payment_id) REFERENCES payment(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_order__order FOREIGN KEY (order_id) REFERENCES order_table(id),
    CONSTRAINT uk_payment_order__payment_order UNIQUE (payment_id, order_id)
);

CREATE INDEX idx_payment_order__payment_id ON payment_order (payment_id);
CREATE INDEX idx_payment_order__order_id ON payment_order (order_id);
COMMENT ON TABLE payment_order IS 'Link between payments and orders';

-- ============================================
-- AUDIT TRIGGERS (FOR UPDATED_AT)
-- ============================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply to all tables with updated_at column
CREATE TRIGGER update_organization_updated_at BEFORE UPDATE ON organization
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_restaurant_updated_at BEFORE UPDATE ON restaurant
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_app_user_updated_at BEFORE UPDATE ON app_user
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_restaurant_access_updated_at BEFORE UPDATE ON user_restaurant_access
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_master_product_category_updated_at BEFORE UPDATE ON master_product_category
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_master_product_updated_at BEFORE UPDATE ON master_product
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_master_menu_template_updated_at BEFORE UPDATE ON master_menu_template
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_master_menu_template_item_updated_at BEFORE UPDATE ON master_menu_template_item
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_product_updated_at BEFORE UPDATE ON product
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_daily_menu_updated_at BEFORE UPDATE ON daily_menu
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_daily_menu_item_updated_at BEFORE UPDATE ON daily_menu_item
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_restaurant_table_updated_at BEFORE UPDATE ON restaurant_table
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_order_table_updated_at BEFORE UPDATE ON order_table
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_order_item_updated_at BEFORE UPDATE ON order_item
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_payment_updated_at BEFORE UPDATE ON payment
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- SCHEMA COMPLETE
-- ============================================
