-- ============================================
-- ADD MENU SECTIONS
-- ============================================

-- Create master_menu_section table
CREATE TABLE master_menu_section (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_template_id  BIGINT NOT NULL,
    name                VARCHAR(120) NOT NULL,
    description         TEXT,
    display_order       INTEGER DEFAULT 0,
    visible             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          BIGINT,
    updated_by          BIGINT,

    CONSTRAINT fk_master_menu_section__master_template FOREIGN KEY (master_template_id) REFERENCES master_menu_template(id) ON DELETE CASCADE,
    CONSTRAINT ck_master_menu_section__name_not_blank CHECK (length(trim(name)) > 0),
    CONSTRAINT uk_master_menu_section__template_name UNIQUE (master_template_id, name)
);

CREATE INDEX idx_master_menu_section__master_template_id ON master_menu_section (master_template_id);
CREATE INDEX idx_master_menu_section__display_order ON master_menu_section (display_order);
COMMENT ON TABLE master_menu_section IS 'Sections within master menu templates (e.g., Entradas, Platos Fuertes, Postres)';

-- Add section_id column to master_menu_template_item
ALTER TABLE master_menu_template_item 
ADD COLUMN section_id BIGINT;

-- Add foreign key for section_id
ALTER TABLE master_menu_template_item
ADD CONSTRAINT fk_master_menu_template_item__section 
FOREIGN KEY (section_id) REFERENCES master_menu_section(id) ON DELETE SET NULL;

-- Add index for section_id
CREATE INDEX idx_master_menu_template_item__section_id ON master_menu_template_item (section_id);

COMMENT ON COLUMN master_menu_template_item.section_id IS 'Optional section grouping for the item';
